name: Synchronize README
on:
  workflow_dispatch:
  issues:
    types: [opened, edited, deleted]
jobs:
  sync-readme:
    runs-on: ubuntu-latest
    name: synchronize the blog readme when issue updated
    steps:
      - name: use local action
        uses: hacker0limbo/my-blog@master
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
